from services.ec2_functions import get_ec2_instances, insert_or_update_ec2_data
from services.cloudtrail_functions import get_all_cloudtrail_events, insert_or_update_cloudtrail_events
from services.rds_functions import get_rds_instances, insert_or_update_rds_data
from services.redshift_functions import get_redshift_clusters, insert_or_update_redshift_data
from services.vpc_functions import get_vpc_details, insert_or_update_vpc_data
from services.subnets_functions import get_subnets_details, insert_or_update_subnet_data
from services.s3_functions import get_s3_buckets, insert_or_update_s3_data
from services.eks_functions import get_eks_clusters, insert_or_update_eks_data